#!/bin/bash -f
# ****************************************************************************
# Vivado (TM) v2022.2.2 (64-bit)
#
# Filename    : simulate.sh
# Simulator   : Xilinx Vivado Simulator
# Description : Script for simulating the design by launching the simulator
#
# Generated by Vivado on Fri Jun 23 01:30:31 EDT 2023
# SW Build 3788238 on Tue Feb 21 19:59:23 MST 2023
#
# IP Build 3783773 on Tue Feb 21 23:41:56 MST 2023
#
# usage: simulate.sh
#
# ****************************************************************************
set -Eeuo pipefail
# simulate design
echo "xsim SIMULATION_behav -key {Behavioral:SIMMING:Functional:SIMULATION} -tclbatch SIMULATION.tcl -view /home/cpmori/Documents/AquaPack/SIMULATION_behav.wcfg -log simulate.log"
xsim SIMULATION_behav -key {Behavioral:SIMMING:Functional:SIMULATION} -tclbatch SIMULATION.tcl -view /home/cpmori/Documents/AquaPack/SIMULATION_behav.wcfg -log simulate.log

